### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Johanna-hub** [chaynHQ/little-window#101]
Chayn needs good documentation to be able to use Little Window:
- [x] Matt King's README suggestions #65  
- [x] Structure of database tables for conversation storing
- [x] Conversation flow in DialogFlow
- [x] Updating Google Sheet with chatbot resources
- [ ] Include video for training of DialogFlow
- [x]  Add information on the emergency intent and how it will be trained
